services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: refreshtokens
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'

